---
title: "Teaching"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```

#Research Tools for Students

##Guide for Research Assistants

##Text Analysis for Writing Students
For students in my writing courses (111 and 210), you may want to conduct some analysis of the texts you are using for your projects.  To do so, there are several ready-made tools that can help you with the analysis.  

###If you are collecting your own texts to analyze

One popular way to analyze texts is to use a concordancer, that will allow you to search for Key Words in Context, see word lists by frequency, and see collocations.  A useful (and free) concordancer is Antconc, created by Lawrence Anthony.
The Compleat Lexical Tutor – if you want a quick analysis of the vocabulary in a text.

Lawrence Anthony’s website – software like AntConc and AntWordProfiler. 

###Web-based corpora

If you want to analyze texts or language use already out there in the universe, there are several web-based tools that allows you to analyze existing data sets.  Here are a few useful 

* [Corpus of Contemporary American English](http://corpus.byu.edu/coca/)
* [The Spoken British National Corpus](https://t.co/RpKT3SkBJG)
* [Corpus of Historical American English](http://corpus.byu.edu/coha/) – if you want to see how language changes over time.
* [SACODEYL](https://www.um.es/sacodeyl/) – A corpus of different European languages with transcripts and video.  The website seems to be abandoned, but most of the materials still work.  
* [MICASE](https://quod.lib.umich.edu/cgi/c/corpus/corpus?c=micase;page=simple) – Michigan Corpus of Academic Spoken English
* [MICUSP](http://micase.elicorpora.info) – Michigan Corpus of Upper-Level Student Papers
* [Trump Twitter Archive](http://trumptwitterarchive.com/archive) – Searchable database of all of Trump's Tweets (and several other related Twitter accounts)
* [Wikipedia Corpus](https://corpus.byu.edu/wiki/) – quickly create your own corpus of Wikipedia articles on related topics.

###Alternative places to get language data
* [The Internet Archive](https://archive.org/) is a valuable repository for classic literature, pop literature, music, and other media that are out of copyright. 
* [TED talks](https://www.ted.com/talks) – Video and transcripts of high-interest presentations by recognized experts. 
* [New South Voices](https://nsv.uncc.edu/) - Interviews from people in the Southeast (especially in the Charlotte area)

#Writing Courses

##The English Next Door

##Engaging in the Conversation

##Advanced Academic Writing

#Global Connections Program

#Other Courses

##But is it Art?
This is a first-year seminar I co-teach with three other faculty members.  In the course, we work as a community of learners to address questions of how to define art and how art is judged and valued.  The students in the course usually keep a [blog](http://questioningartwfu.blogspot.com) of their work and experiences.  

## Computer Assisted Language Learning
Several years ago, I taught a [course on uses of technology in Language Learning.](https://sites.google.com/site/callnau/)  The information is largely outdated, but the students in this course made a useful wiki of our course readings and activities.  




To update: teaching files and materials